version: 2
updates:
  - package-ecosystem: "github-actions" # search for actions - there are other options available
    directory: "/" # search in .github/workflows under root `/`
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform" 
    directory: "/01_Foundation"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform" 
    directory: "/02_Storage"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform" 
    directory: "/03_etc_etc"
    schedule:
      interval: "weekly"
