name: "01_Foundation"

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master
 # pull_request:

# Set the working directory to main for the config files
defaults:
  run:
    shell: bash
    working-directory: 01_Foundation

env:
  TF_VERSION: latest                   #Optional
  TF_STATE_NAME: 01_Foundation         #Required
  TF_CONTAINER_NAME: ghdeploytfstate   #Required
  ENVIRONMENT: Development             #Required

jobs:
  build-plan:
    name: "01_Foundation_Plan"
    uses: Pwd9000-ML/Azure-Terraform-Deployments/.github/workflows/tf_plan.yml@master
    with:
      tf_version: ${{ env.TF_VERSION }}               #Optional
      tf_state_name: ${{ env.TF_STATE_NAME }}         #Required
      tf_container_name: ${{ env.TF_CONTAINER_NAME }} #Required
      environment: ${{ env.ENVIRONMENT }}             #Required
    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      resource_group: ${{ secrets.RESOURCE_GROUP }}
      storage_account: ${{ secrets.STORAGE_ACCOUNT }}


