name: "01_Foundation"

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master
 # pull_request:

# Set the working directory to main for the config files
defaults:
  run:
    shell: bash
    working-directory: 01_Foundation

jobs:
  
  Build_01_Foundation:
    uses: Pwd9000-ML/Azure-Terraform-Deployments/.github/workflows/tf_plan.yml@master
    with:
      path: 01_Foundation                #Optional
      tf_version: latest                 #Optional
      tf_key: foundation                 #Required
      tf_container_name: ghdeploytfstate #Required
      environment: Development           #Required
    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      resource_group: ${{ secrets.RESOURCE_GROUP }}
      storage_account: ${{ secrets.STORAGE_ACCOUNT }}
