name: "From_Marketplace_Example"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  Plan_Dev:
    runs-on: ubuntu-latest
    environment: null
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Development TF Plan
        uses: Pwd9000-ML/terraform-azurerm-plan@master
        with:
          path: 01_Foundation                ## Path to terraform root module (Required)
          az_resource_group: TF-Core-Rg      ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
          az_storage_acc: tfcorebackendsa    ## AZ backend - AZURE terraform backend storage acc (Required)
          az_container_name: ghdeploytfstate ## AZ backend - AZURE storage container hosting state files (Required)
          tf_key: foundation-dev             ## AZ backend - Specifies name that will be given to terraform state file (Required)
          tf_vars_file: config-dev.tfvars    ## Terraform TFVARS (Required)
          enable_TFSEC: true
          arm_client_id: ${{ secrets.ARM_CLIENT_ID }}             ## ARM Client ID 
          arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}     ## ARM Client Secret
          arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }} ## ARM Subscription ID
          arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}             ## ARM Tenant ID