name: "Marketplace-Example-Tests2"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  Run_Tests:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Plan-Apply-Destroy
        uses: Pwd9000-ML/terraform-azurerm-tests@master
        with:
          test_type: plan-apply ## Valid options are "plan", "plan-apply", "plan-apply-destroy" Default="plan"
          path: 01_Foundation
          tf_vars_file: config-tests.tfvars
          tf_key: foundation-tests
          az_resource_group: TF-Core-Rg
          az_storage_acc: tfcorebackendsa
          az_container_name: ghdeploytfstate
          arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
          arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}